### PR TITLE
Compatibility with Dolibarr 10.x. Added spanish translation.

### PR DESCRIPTION
**Pull request by caos30**
Foloowing the suggestion of @wdammak i've done this frk and this first PULL REQUEST.

It contains probably about one hundred of hours working on this double module (Prestashop/Dolibarr). 

The main contributions:
- compatibility with Dolibarr 10
- now it pass too product pictures :-)
- added some keys to translations
- translated to es_ES & es_MX (really both are equal, but i need it for my customers on mexico)

Comments:
- in the first Prestashop instance that i'm using it, it worked fine the first time with few products, synchronizing to Dolibarr the new products. But now that has been migrated almost 8,000 products and there is more than 11,000 to be passed to Dolibarr, i get an error. I must work on it the next month.
- i've added a button "how many" on the Export tab of the module, to show information about number of objects on database and number of objects already exported. Todo: maybe this info could be added on this HTML table in 2 new columns, instead to use JSON for get info and render it with an alert() popup message.
- i've not almost tested orders and invoices synchronization. In the few tests i've done i got it work fine. But i suppose that the more intensive use of this first website will give us more information.

### CODE REVIEW

**Comment by wdammak** [comment]
@johanbernard could you check the PR and validate it please?

**Comment by wdammak** [comment]
@caos30 @johanbernard 
I revised the code a bit, here are my comments:
- On the dolibarr module side at code level nothing is overwhelming! Just make sure that the products with multi-images migred correctly!
- Prestashop side, in the importClients function why you deleted the $code_postal, $city, $country_code_iso, $telephone synch, maybe i forgot to pay attention to a new added function enrichAddress but it seems to me is not called in importClients?
- about the migration error of a large number of products: have you tried to change this public value $nbr_max_sec_export = 10;?
- why class InterfaceDolipresta //extends DolibarrTriggers ? is not DolibarrTriggers ?

Overall I think that the PR is good and can be validated to be able to improve it a little (The possibility of company edition from dol to presta is easy to add)

THANKS!

**Comment by wdammak** [comment]
Sorry! After the tests with dolibarr11 <-> presta1.6.23, I have errors with the category export

Also for the export of products: ProductModuleNotSetupForAutoRef
Notice on line 2948: modules\prestashoptodolibarrpro\prestashoptodolibarrpro.php
[8] Undefined offset: 0

I will try to debug

**Comment by caos30** [comment]
Hello @wdammak thanks for your time to check my PR. About your comments:

- Yes, i certainly dedicated a lot of more time on the prestashop module, than on the Dolibarr module. Because i really like the Prestashop interface for manage products (is more user friendly) more than the Dolibarr interface. Furthermore, as you know, you can sync several prestashops with a unique Dolibarr. So i understand that the logical direction is this: create the products on Prestashop and after export to Dolibarr. Correct me if i'm wrong, please.
- I don't remember perfectly what i do because i did those changes at least 2 months ago. But, i would say that some fields has been removed in the last versions of Dolibarr (i worked with Dolibarr 10.x) respect the old versions of Dolibarr. If not removed, change of name or moved to another "object type" ("contacts" maybe, instead of "third parties"). I mention this because i would say that for this reason and due to my hurry to get a minimal functional version i removed -perhaps- some fields. Sincerely, i'm not very sure.
- The error on migration products now (after 8,000 products) i'm not sure that it's because the great number of products. I say it because the export fails INMEDIATELY after click the button. You know: it doesn't get broken after 30-60 seconds "working"... it seems that fail in the first istant. But don't worry about this, because i think that probably is another problem realted, who knows... something new perhaps appeared in a new product which has something different than others. Do you understand me? Sincerely, i've not had time to check it since more than a month ago... :-( 
- Regarding extends class, again i don't remember why. I remember that i had to do it to make it run. I think that i take the formula to use from the "example module" that comes on Dolibarr for developers. 

By the way, my speak english is not very good, but i would feel more comfortable to be able to talk with you by chat. Whatsapp maybe? Take my number, please: +526621041362 (i will remove this paragraph from here once you contact me by there) or by Telegram (same number). Cheers.

**Comment by johanbernard** [comment]
La branche a un conflit avec ce qui est déjà en ligne, du coup je ne peux pas l'importer mais peut être que les autres commit déjà en ligne apportent ces update

**Comment by caos30** [comment]
I'm sorry, but I don't understand your french comment, even using google translator (it translated something without sense).

But the automatic english message of Github below yours suggest that there is a so complex conflict that it cannot be solved using the web editor.

So i suspect -as i told the first day several weeks ago in my first comment- that my changes on your project are so deep that it probably is very difficult to be considered a "fork + light modification". I rewrote too much things, event the definition of the class for Dolibarr 10, as you know and commented above some days ago. 

Please, tell me what can i do. Can i give you rights/permissions over to you my own fork and then you can touch it? I ask this because sincerely i'm not an advanced used on Github tools. My usual PR has been always "little" for other projects.

**Comment by caos30** [comment]
Hello @johanbernard & @wdammak  i finally have found how to solve the conflicts for PR. The "problem" was that you did a couple of commits since i made the first fork of your repository some months ago. 

So i updated and rebase my repository with your last commits on your repo, solved the unique conflict and pushed my changes to my repo, so now Github is showing that the PR HAS NO CONFLICTS :-)

Thanks! One always learns new things with git, hehehe.
Cheers!

**Comment by wdammak** [comment]
@caos30 
Thx, it's noted, when I come back to europe after confinement
Please add this change to line 359 in admin_dolipresta.php 
$url = $urlBoutique.'api/order_states?display=%5Bid%2C%20name%5D';

**Comment by wdammak** [comment]
@caos30 
get admin_dolipresta.php
https://github.com/johanbernard/prestashop_to_dolibarr/pull/16

**Pull request merged**
